### ISSUE TITLE
create/update/delete requests

### ISSUE THREAD

**Issue by agamaya-user** [woohoolabs/yang#14]
Is it possible to use library to generate create/update/delete requests?

**Comment by kocsismate** [comment]
Absolutely!

Have a look at the concerning part of the read me: https://github.com/woohoolabs/yang#request-builder

You can either use the request builder to set the HTTP method to `POST`/`PATCH`/`DELETE` (with `$requestBuilder::setMethod()`) or you can do the same with a PSR-7 compliant request object like this: `$request = $request->withMethod("POST")`.
