### ISSUE TITLE
Allow access to ResourceObject.id

### ISSUE THREAD

**Issue by holtkamp** [woohoolabs/yang#15]
Currently the [ResourceObject.id](https://github.com/woohoolabs/yang/blob/1fcf20d55def5983775e19e5c52a8dc46cc14f15/src/JsonApi/Request/ResourceObject.php#L16) property is private and can therefore not be accessed once the object is instantiated. Is this on purpose?

**Rationale**
I would like to be to access it, so the id can be used to (dynamically) generate a DELETE request like:

```
https://domain.ext/api/v1/resourceName/id/$id
```

Something like:

```php
//application.php
$articleResource = ArticleResource::getInstance(123);
if( $apiClient->delete($articleResource)){
    echo 'deleted Article!';
}
```

```php
//apiClient.php
public function delete(Resource $resource) : bool{
    $request = $this->someRequestBuilder->getDeleteRequest($articleResource)
    $response = $this->sendRequest($request);
    return $this->analyzeRespons($response);
}
```

Maybe the ResourceObject.id *should* not be accessed, that is possible, but in that case I would like to know "why" 😄

**Comment by kocsismate** [comment]
Hi @holtkamp,

The only purpose of the id field being private without any getter/setter is that I didn't have any meaningful use-case for being able to access these fields in mind.

Would it be OK for you if I added the `id()`, `type()`, `attributes()` and `relationships()` accessors as well as the `setId()` and `setType()` mutators?

**Comment by kocsismate** [comment]
Done in https://github.com/woohoolabs/yang/commit/fb539603f759a0fb410c66e65b0e186ee9eec75b :)
