### ISSUE TITLE
Missing type hinting

### ISSUE THREAD

**Issue by porchlight** [woohoolabs/yang#37]
Ran into this error when trying to use this on my Drupal 10 site.

`Fatal error: Declaration of WoohooLabs\Yang\JsonApi\Response\AbstractResponse::withStatus($code, $reasonPhrase = '') must be compatible with Psr\Http\Message\ResponseInterface::withStatus(int $code, string $reasonPhrase = ''): Psr\Http\Message\ResponseInterface in /var/www/site/vendor/woohoolabs/yang/src/JsonApi/Response/AbstractResponse.php on line 136`

The error comes from psr/http-message:^2.0  which Drupal 10 requires. 
Looks like we need to add some type hinting to the parameters and return types of some of the methods we are extending from `ResponseInterface` and `MessageInterface`

**Comment by porchlight** [comment]
Nevermind! Just needed to update to the 3.0 version. Thanks

**Comment by kocsismate** [comment]
Thanks for the report anyway! I'll release v3.0 tomorrow then :)
